# Generated by Django 6.0.2 on 2026-02-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(choices=[('base', 'Base'), ('cream', 'Crème'), ('filling', 'Fourrage'), ('glaze', 'Glaçage'), ('decoration', 'Décoration')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Commun'), ('uncommon', 'Peu commun'), ('rare', 'Rare'), ('epic', 'Épique')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('flavor', models.CharField(max_length=50)),
                ('gout', models.IntegerField()),
                ('technique', models.IntegerField()),
                ('esthetique', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('money', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='cards.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='cards.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='cards.player')),
            ],
        ),
        migrations.CreateModel(
            name='CardInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_base', to='cards.cardinstance')),
                ('cream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_cream', to='cards.cardinstance')),
                ('decorations', models.ManyToManyField(related_name='team_decorations', to='cards.cardinstance')),
                ('filling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_filling', to='cards.cardinstance')),
                ('glaze', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_glaze', to='cards.cardinstance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.player')),
            ],
        ),
    ]
