# Generated by Django 6.0.2 on 2026-02-25 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('bonus_type', models.CharField(choices=[('classique', 'Duel classique'), ('technique', 'Technique'), ('thematique', 'Thématique')], default='classique', max_length=20)),
                ('gout_multiplier', models.FloatField(default=1.0)),
                ('technique_multiplier', models.FloatField(default=1.0)),
                ('esthetique_multiplier', models.FloatField(default=1.0)),
                ('bonus_percentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.AddField(
            model_name='match',
            name='teamP1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='cards.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='teamP2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='cards.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='cards.team'),
        ),
    ]
