# Generated by Django 6.0.2 on 2026-03-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_player_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinstance',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
