# Generated by Django 6.0.2 on 2026-03-22 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardinstance_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinstance',
            name='esthetique_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardinstance',
            name='gout_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardinstance',
            name='technique_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='cream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_cream', to='cards.cardinstance'),
        ),
    ]
